/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "uart_driver.h"

#define F_CPU 16000000UL

int read_memory(char[]);
void write_memory(char[]);
void dump_memory(char[]);

// main
int main(void) {
  init_usart2(19200, F_CPU);

  char input[100];
  char* token;

  while (1) {

	  fgets(input, 100, stdin);
	  token = strpbrk(input, "rwd");

	  switch (token?*token:-1) {
	  case 'r':
		  printf("Reading Memory\n");
		  int output = read_memory(input);

		  printf("\tHex: 0x%x\n", output);
		  printf("\tDec: %d\n", output);
		  break;
	  case 'w':
		  printf("Writing Memory\n");
		  break;
	  case 'd':
		  printf("Dumping Memory\n");
		  break;
	  }
  }

  return 0;
}

int read_memory(char input[]) {
  int address;

  sscanf(input, "%s %x", input, &address);

  volatile int* address_pointer = (int*) address;

  return *address_pointer;
}

void write_memory(char input[]) {

}

void dump_memory(char input[]) {

}
