/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/



#include <stdio.h>
#include <stdlib.h>
#include "uart_driver.h"
#include "embedded.h"

#define F_CPU 16000000UL
#define delay 100

// main
int main(void){

	init_usart2(19200, F_CPU);

	LED_INIT();

	int number = 1;

	while (1) {
		for (int i = 0; i < 9; i++) {
			light_LED(number);
			delay_ms(delay);
			number = number << 1;
		}
		for (int i = 0; i < 9; i++) {
			light_LED(number);
			delay_ms(delay);
			number = number >> 1;
		}
	}
}

